import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { ForgejoApi } from "@intentic/providers";

// The repo Actions secrets the INTENT pipeline pushes the resolved artifact into the desired-state repo with
// (HTTP Basic against Forgejo, the same scheme `adopt` pushes with). The token is the Forgejo admin password.
export const GIT_USER_SECRET = "INTENTIC_GIT_USER";
export const GIT_TOKEN_SECRET = "INTENTIC_GIT_TOKEN";

// The job env-var names the resolve pipeline binds those secrets to (and that the CLI reads): the resolve sync
// authenticates its Forgejo secret PUTs with GIT_TOKEN (the admin password).
export const GIT_USER_ENV = "GIT_USER";
export const GIT_TOKEN_ENV = "GIT_TOKEN";

// The package the pipelines install the CLI from. The intent/desired-state repos do not depend on the CLI
// (only on @intentic/{sdk,graph}); the runner pulls it on demand via `pnpm dlx`, pinned to the adopting CLI's
// own version so the pipeline runs the same intentic the operator bootstrapped with.
const CLI_PACKAGE = "@intentic/cli";
// The git ref the apply pipeline force-moves onto each SUCCESSFULLY-applied commit. The next apply diffs the
// new artifact against the artifact at this tag (the last good state) to decide what to prune — so a failed
// apply, which never reaches the tag step, never corrupts the prune baseline.
const APPLIED_TAG = "intentic-applied";

export const INTENT_WORKFLOW_PATH = ".forgejo/workflows/resolve.yaml";
export const APPLY_WORKFLOW_PATH = ".forgejo/workflows/apply.yaml";

// Forgejo rejects an Actions secret whose name starts with a reserved prefix (HTTP 400 "invalid secret
// name"), so a generated key like FORGEJO_ADMIN_PASSWORD cannot be stored verbatim. Map such keys to an
// INTENTIC_-prefixed STORE name; the workflow binds the original env-var name to this store name, so the CLI
// still reads the real key. Used on both sides (the PUT and the `${{ secrets.* }}` reference) so they agree.
const RESERVED_SECRET_PREFIXES = ["GITHUB_", "GITEA_", "FORGEJO_"];
export const forgejoSecretName = (key: string): string =>
    RESERVED_SECRET_PREFIXES.some((prefix) => key.startsWith(prefix)) ? `INTENTIC_${key}` : key;

export interface PipelineInputs {
    // The adopting CLI's version, baked into `pnpm dlx @intentic/cli@<version>` in both pipelines.
    readonly cliVersion: string;
    // The Forgejo admin user — the repo owner and the git-push identity.
    readonly user: string;
    // The public git domain (git.<zone>); the REST + clone-url authority.
    readonly domain: string;
    // The intent config the resolve pipeline reads and the artifact it writes (bare names within each repo).
    readonly configFile: string;
    readonly artifactFile: string;
    // The repo names under the admin owner.
    readonly intentRepo: string;
    readonly desiredStateRepo: string;
    // Every secret key the apply pipeline injects into the job env (the graph's env + generated secrets) —
    // `apply` resolves each from process.env, and the generated ones win over `.secrets.json` (env-first).
    readonly applySecretKeys: readonly string[];
    // The generated secret key holding the Forgejo admin password; the apply pipeline pushes the applied-tag
    // with it (admin Basic auth), so no separate git-push secret is needed on the desired-state repo.
    readonly forgejoPasswordKey: string;
}

const cloneUrl = (inputs: PipelineInputs, repo: string): string => `https://${inputs.domain}/${inputs.user}/${repo}.git`;

// On a push that changes the authored config, resolve it into a fresh artifact and push that into the
// desired-state repo (whose own pipeline then applies it). The desired-state clone/push authenticates with the
// INTENTIC_GIT_* repo secrets via http.extraHeader, so credentials never touch .git/config.
export const intentWorkflowYaml = (inputs: PipelineInputs): string =>
    [
        "# Generated by intentic: resolve deploy.config.ts and push the new artifact into the desired-state repo.",
        "on:",
        "  push:",
        '    branches: [ "main" ]',
        `    paths: [ "${inputs.configFile}", "package.json", "pnpm-lock.yaml" ]`,
        "jobs:",
        "  resolve:",
        "    runs-on: docker",
        "    env:",
        `      CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}`,
        `      ${GIT_USER_ENV}: \${{ secrets.${GIT_USER_SECRET} }}`,
        `      ${GIT_TOKEN_ENV}: \${{ secrets.${GIT_TOKEN_SECRET} }}`,
        "    steps:",
        "      - uses: https://github.com/actions/checkout@v4",
        "      - name: resolve and push desired-state",
        "        run: |",
        "          corepack enable",
        "          pnpm install --ignore-workspace",
        '          AUTH="$(printf \'%s:%s\' "$GIT_USER" "$GIT_TOKEN" | base64 -w0)"',
        `          git -c http.extraHeader="Authorization: basic $AUTH" clone ${cloneUrl(inputs, inputs.desiredStateRepo)} /tmp/ds`,
        `          pnpm dlx ${CLI_PACKAGE}@${inputs.cliVersion} resolve --config ${inputs.configFile} --out /tmp/ds/${inputs.artifactFile} --sync-control-plane`,
        "          cd /tmp/ds",
        "          git add -A",
        "          if git diff --cached --quiet; then echo 'desired-state unchanged'; exit 0; fi",
        `          git -c user.name="${inputs.user}" -c user.email="${inputs.user}@${inputs.domain}" commit -m "intentic resolve"`,
        '          git -c http.extraHeader="Authorization: basic $AUTH" push origin HEAD:main',
        "",
    ].join("\n");

// On a push that changes the artifact, apply it. Full history is fetched so the last successfully-applied
// commit (tagged `intentic-applied`) can be read as the prune baseline. On success the tag is force-moved onto
// the applied commit and pushed, so it always points at the last good state.
export const applyWorkflowYaml = (inputs: PipelineInputs): string => {
    const env = inputs.applySecretKeys.map((key) => `      ${key}: \${{ secrets.${forgejoSecretName(key)} }}`);
    return [
        "# Generated by intentic: apply the desired-state artifact, pruning resources it no longer declares.",
        "on:",
        "  push:",
        '    branches: [ "main" ]',
        `    paths: [ "${inputs.artifactFile}" ]`,
        "jobs:",
        "  apply:",
        "    runs-on: docker",
        "    env:",
        ...env,
        "    steps:",
        "      - uses: https://github.com/actions/checkout@v4",
        "        with:",
        "          fetch-depth: 0",
        "      - name: apply and prune",
        "        run: |",
        "          corepack enable",
        "          PREV=''",
        `          if git rev-parse -q --verify refs/tags/${APPLIED_TAG} >/dev/null; then \\`,
        `            git show ${APPLIED_TAG}:${inputs.artifactFile} > /tmp/previous.json && PREV="--previous /tmp/previous.json"; fi`,
        `          pnpm dlx ${CLI_PACKAGE}@${inputs.cliVersion} apply --artifact ${inputs.artifactFile} $PREV`,
        "      - name: mark applied",
        "        run: |",
        `          AUTH="$(printf '%s:%s' '${inputs.user}' "$${inputs.forgejoPasswordKey}" | base64 -w0)"`,
        `          git tag -f ${APPLIED_TAG} HEAD`,
        `          git -c http.extraHeader="Authorization: basic $AUTH" push -f origin refs/tags/${APPLIED_TAG}`,
        "",
    ].join("\n");
};

// Write a workflow file into a local repo dir (creating .forgejo/workflows/), so `adopt`'s normal add/commit/
// push carries it — no API commit, no extra trigger.
export const writeWorkflow = async (repoDir: string, workflowPath: string, content: string): Promise<void> => {
    const full = join(repoDir, workflowPath);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, content);
};

// Seed both control-plane repos with their pipelines, before the push that adopts them.
export const writeControlPlaneWorkflows = async (intentDir: string, targetDir: string, inputs: PipelineInputs): Promise<void> => {
    await writeWorkflow(intentDir, INTENT_WORKFLOW_PATH, intentWorkflowYaml(inputs));
    await writeWorkflow(targetDir, APPLY_WORKFLOW_PATH, applyWorkflowYaml(inputs));
};

// Set a repo's Actions secrets from a name -> value map, after the repo exists (post-adopt push).
export const setRepoSecrets = async (args: {
    readonly api: ForgejoApi;
    readonly baseUrl: string;
    readonly user: string;
    readonly password: string;
    readonly owner: string;
    readonly name: string;
    readonly secrets: Readonly<Record<string, string>>;
}): Promise<void> => {
    for (const [secretName, data] of Object.entries(args.secrets)) {
        await args.api.setRepoSecret({
            baseUrl: args.baseUrl,
            user: args.user,
            password: args.password,
            owner: args.owner,
            name: args.name,
            secretName: forgejoSecretName(secretName),
            data,
        });
    }
};
