import type { Provider, ResolvedInputs } from "@intentic/engine";
import { z } from "zod";
import { composeDown, composeUp, containerImage, restampBacking, stateDir, waitReady } from "../core/backing-ssh.js";
import { parseInputs, sshSchema, sshTarget } from "../core/inputs.js";
import type { SshSession } from "../core/ssh.js";
import { type SshExecutor, sshExecutor } from "../core/ssh.js";

const KIND = "postgres";
const READY_TIMEOUT_MS = 120_000;

const postgresSchema = sshSchema.extend({
    internalIp: z.string(),
    // The host port the instance publishes 5432 on (resolver-assigned, disjoint per instance).
    publishPort: z.number(),
    // The superuser password, generated by intentic. Set on first init so TCP connections require a password;
    // per-app roles (minted by the binding provider) authenticate with their own passwords.
    adminPassword: z.string(),
    image: z.string(),
});
type PostgresInputs = z.infer<typeof postgresSchema>;
const parse = (inputs: ResolvedInputs): PostgresInputs => parseInputs(postgresSchema, inputs, KIND);

const outputsFor = (parsed: PostgresInputs): Record<string, unknown> => ({
    internalHost: parsed.internalIp,
    port: String(parsed.publishPort),
});

// A single Postgres service published on the host's internal ip; the named volume survives a pin bump so the
// data persists. The superuser password is interpolated from the write-once .env. Stamped intentic.id=<id>
// so the binding provider can docker-exec into it.
const composeYaml = (id: string, parsed: PostgresInputs): string =>
    [
        "services:",
        "  postgres:",
        `    image: ${parsed.image}`,
        "    restart: unless-stopped",
        "    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: $POSTGRES_PASSWORD, POSTGRES_DB: postgres }",
        "    volumes: [ data:/var/lib/postgresql/data ]",
        `    ports: [ "${parsed.publishPort}:5432" ]`,
        `    labels: [ "intentic.id=${id}" ]`,
        "    healthcheck:",
        "      test: [ CMD-SHELL, pg_isready -U postgres ]",
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 10",
        "volumes: { data: {} }",
        "",
    ].join("\n");

// Write compose (always) + .env (once — the superuser password is baked into the data dir on first init and
// Postgres ignores it thereafter, so re-keying would lock us out).
const ensureFiles = async (session: SshSession, id: string, parsed: PostgresInputs): Promise<void> => {
    const dir = stateDir(KIND, id);
    await session.exec(`mkdir -p ${dir}`);
    await session.exec(`cat > ${dir}/compose.yaml <<'COMPOSE_EOF'\n${composeYaml(id, parsed)}COMPOSE_EOF`);
    await session.exec(`test -f ${dir}/.env || printf 'POSTGRES_PASSWORD=%s\\n' '${parsed.adminPassword}' > ${dir}/.env && chmod 600 ${dir}/.env`);
};

const readyProbe = (id: string): string =>
    `cid=$(docker ps -q --filter "label=intentic.id=${id}"); [ -n "$cid" ] && docker exec "$cid" pg_isready -U postgres -q`;

// A Postgres backing instance (i.want.database). read returns the resource only once the container is up and
// pg_isready passes (so a noop re-derives the deterministic internalHost/port); diff drives an image-pin bump;
// apply is idempotent (compose up -d reconciles, the volume persists). Per-app databases are the binding
// provider's job, not this one's.
export const createPostgresProvider = (executor: SshExecutor = sshExecutor): Provider => ({
    read: async (inputs, ctx) => {
        const parsed = parse(inputs);
        let session: SshSession;
        try {
            session = await executor.connect(sshTarget(parsed));
        } catch (error) {
            ctx.log(`postgres "${ctx.id}": host not reachable over SSH, treating as not-yet-created: ${String(error)}`);
            return undefined;
        }
        try {
            const probe = await session.exec(readyProbe(ctx.id));
            if (probe.code !== 0) {
                return undefined;
            }
            return { outputs: outputsFor(parsed), detail: { image: await containerImage(session, ctx.id) } };
        } finally {
            await session.dispose();
        }
    },
    diff: (inputs, observed) => {
        const parsed = parse(inputs);
        const image = (observed.detail?.["image"] ?? "") as string;
        return image === parsed.image
            ? { action: "noop" }
            : { action: "update", reason: `postgres image differs (running ${image}, want ${parsed.image})` };
    },
    apply: async (inputs, _observed, ctx) => {
        const parsed = parse(inputs);
        const session = await executor.connect(sshTarget(parsed));
        try {
            await ensureFiles(session, ctx.id, parsed);
            await composeUp(session, KIND, ctx.id);
            await waitReady(session, KIND, ctx.id, readyProbe(ctx.id), READY_TIMEOUT_MS);
            return outputsFor(parsed);
        } finally {
            await session.dispose();
        }
    },
    delete: async (inputs, ctx) => {
        const parsed = parse(inputs);
        const session = await executor.connect(sshTarget(parsed));
        try {
            await composeDown(session, KIND, ctx.id);
        } finally {
            await session.dispose();
        }
    },
    // Inputs are resolved leniently (the new node's internalIp ref is absent), so parse only the SSH block to
    // connect; the image (a literal) drives the volume-copy container.
    restamp: async (oldId, inputs, ctx) => {
        const target = sshTarget(parseInputs(sshSchema, inputs, KIND));
        const image = typeof inputs["image"] === "string" ? inputs["image"] : "busybox";
        const session = await executor.connect(target);
        try {
            await restampBacking(session, KIND, oldId, ctx.id, image);
        } finally {
            await session.dispose();
        }
    },
});
