import type { Provider, ResolvedInputs } from "@intentic/engine";
import { z } from "zod";
import type { GitHubApi } from "./github-api.js";
import { githubApi } from "./github-api.js";
import { parseInputs } from "./inputs.js";

const ghCiSchema = z.object({
    owner: z.string(),
    repoName: z.string(),
    branch: z.string(),
    tag: z.string(),
    token: z.string(),
    // Host connection for the SSH deploy step in the workflow.
    hostAddress: z.string(),
    deploymentId: z.string(),
    port: z.coerce.number(),
    env: z.record(z.string(), z.unknown()).default({}),
});
type GhCiInputs = z.infer<typeof ghCiSchema>;
const parse = (inputs: ResolvedInputs): GhCiInputs => parseInputs(ghCiSchema, inputs, "gh-ci");

const workflowPath = (tag: string): string => `.github/workflows/deploy-${tag}.yml`;
const DOCKERFILE_PATH = "Dockerfile";

const SECRET_SSH_KEY = "INTENTIC_HOST_SSH_KEY";
const SECRET_HOST_ADDRESS = "INTENTIC_HOST_ADDRESS";
const SECRET_HOST_USER = "INTENTIC_HOST_USER";

// A minimal starter Dockerfile (same as the Forgejo path).
const starterDockerfile = (): string =>
    [
        "# intentic starter Dockerfile — replace with your app's real build.",
        "FROM busybox",
        "RUN mkdir -p /www && printf '%s' 'intentic: replace this Dockerfile with your app' > /www/index.html",
        "ENV PORT=8080",
        "EXPOSE 8080",
        'CMD ["sh","-c","httpd -f -v -p $PORT -h /www"]',
        "",
    ].join("\n");

// The GitHub Actions workflow: builds the Dockerfile, pushes to GHCR, SSHes into the host to deploy.
const workflowYaml = (parsed: GhCiInputs): string => {
    const image = `ghcr.io/${parsed.owner}/${parsed.repoName}`;
    const envLines = Object.entries(parsed.env)
        .map(([key, value]) => `-e ${key}='${String(value)}'`)
        .join(" \\\n              ");
    const envFlag = envLines.length > 0 ? ` \\\n              ${envLines}` : "";

    return [
        "# Generated by intentic: build → push to GHCR → deploy via SSH.",
        `name: deploy-${parsed.tag}`,
        "on:",
        "  push:",
        `    branches: ["${parsed.branch}"]`,
        "jobs:",
        "  deploy:",
        "    runs-on: ubuntu-latest",
        "    permissions:",
        "      contents: read",
        "      packages: write",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "      - uses: docker/login-action@v3",
        "        with:",
        "          registry: ghcr.io",
        "          username: ${{ github.actor }}",
        "          password: ${{ secrets.GITHUB_TOKEN }}",
        "      - uses: docker/build-push-action@v6",
        "        with:",
        "          context: .",
        "          push: true",
        "          tags: |",
        `            ${image}:${parsed.tag}`,
        `            ${image}:$\{{ github.sha }}`,
        "      - name: deploy to host",
        "        uses: appleboy/ssh-action@v1",
        "        with:",
        `          host: \${{ secrets.${SECRET_HOST_ADDRESS} }}`,
        `          username: \${{ secrets.${SECRET_HOST_USER} }}`,
        `          key: \${{ secrets.${SECRET_SSH_KEY} }}`,
        "          script: |",
        `            docker pull ${image}:${parsed.tag}`,
        `            docker stop ${parsed.deploymentId} || true`,
        `            docker rm ${parsed.deploymentId} || true`,
        `            docker run -d --name ${parsed.deploymentId} --restart unless-stopped \\`,
        `              -p ${parsed.port}:${parsed.port}${envFlag} \\`,
        `              ${image}:${parsed.tag}`,
        "",
    ].join("\n");
};

const normalize = (yaml: string): string =>
    yaml
        .split("\n")
        .map((line) => line.replace(/\s+$/, ""))
        .join("\n")
        .trim();

// The app's CI/CD wiring for the GitHub path: commits the GitHub Actions workflow and sets the host SSH
// secrets it consumes. Mirrors ci.ts but generates a GitHub Actions workflow instead of Forgejo Actions.
export const createGhCiProvider = (api: GitHubApi = githubApi): Provider => ({
    read: async (inputs, ctx) => {
        if (typeof inputs["token"] !== "string" || typeof inputs["owner"] !== "string") {
            return undefined;
        }
        const parsed = parse(inputs);
        try {
            const file = await api.readFile({
                token: parsed.token,
                owner: parsed.owner,
                repo: parsed.repoName,
                path: workflowPath(parsed.tag),
                branch: parsed.branch,
            });
            if (file === undefined) {
                return undefined;
            }
            return { outputs: {}, detail: { workflow: file.content } };
        } catch (error) {
            ctx.log(`gh-ci "${ctx.id}": GitHub not reachable yet: ${String(error)}`);
            return undefined;
        }
    },
    diff: (inputs, observed) => {
        const workflow = observed.detail?.["workflow"];
        if (typeof workflow !== "string" || normalize(workflow) !== normalize(workflowYaml(parse(inputs)))) {
            return { action: "update", reason: "GitHub Actions workflow differs from desired" };
        }
        return { action: "noop" };
    },
    apply: async (inputs) => {
        const parsed = parse(inputs);
        const common = { token: parsed.token, owner: parsed.owner, repo: parsed.repoName };

        // Set the host SSH secrets the workflow's deploy step uses.
        await api.setRepoSecret({ ...common, secretName: SECRET_SSH_KEY, value: "placeholder-ssh-key" });
        await api.setRepoSecret({ ...common, secretName: SECRET_HOST_ADDRESS, value: parsed.hostAddress });
        await api.setRepoSecret({ ...common, secretName: SECRET_HOST_USER, value: "deploy" });

        // Seed a starter Dockerfile if the repo has none.
        const dockerfile = await api.readFile({ ...common, path: DOCKERFILE_PATH, branch: parsed.branch });
        if (dockerfile === undefined) {
            await api.commitFile({ ...common, path: DOCKERFILE_PATH, content: starterDockerfile(), branch: parsed.branch, message: "intentic: starter Dockerfile" });
        }

        // Commit the workflow LAST so its first run already sees the Dockerfile + secrets.
        const existing = await api.readFile({ ...common, path: workflowPath(parsed.tag), branch: parsed.branch });
        await api.commitFile({
            ...common,
            path: workflowPath(parsed.tag),
            content: workflowYaml(parsed),
            branch: parsed.branch,
            message: "intentic: GitHub Actions workflow",
            ...(existing !== undefined ? { sha: existing.sha } : {}),
        });
        return {};
    },
    delete: async (inputs) => {
        if (typeof inputs["token"] !== "string" || typeof inputs["owner"] !== "string") {
            return;
        }
        const parsed = parse(inputs);
        const common = { token: parsed.token, owner: parsed.owner, repo: parsed.repoName };
        await api.deleteFile({ ...common, path: workflowPath(parsed.tag), branch: parsed.branch, message: "intentic: remove workflow" });
        await api.deleteRepoSecret({ ...common, secretName: SECRET_SSH_KEY });
        await api.deleteRepoSecret({ ...common, secretName: SECRET_HOST_ADDRESS });
        await api.deleteRepoSecret({ ...common, secretName: SECRET_HOST_USER });
    },
});
