import type { Provider, ResolvedInputs } from "@intentic/engine";
import { z } from "zod";
import { composeDown, composeUp, containerImage, stateDir, waitReady } from "./backing-ssh.js";
import { parseInputs, sshSchema, sshTarget } from "./inputs.js";
import type { SshSession } from "./ssh.js";
import { type SshExecutor, sshExecutor } from "./ssh.js";

const KIND = "valkey";
const READY_TIMEOUT_MS = 60_000;

const valkeySchema = sshSchema.extend({
    internalIp: z.string(),
    publishPort: z.number(),
    // The admin password (requirepass), generated by intentic. The binding provider reuses it to run
    // ACL SETUSER for per-app users.
    adminPassword: z.string(),
    image: z.string(),
});
type ValkeyInputs = z.infer<typeof valkeySchema>;
const parse = (inputs: ResolvedInputs): ValkeyInputs => parseInputs(valkeySchema, inputs, KIND);

const outputsFor = (parsed: ValkeyInputs): Record<string, unknown> => ({
    internalHost: parsed.internalIp,
    port: String(parsed.publishPort),
});

// A single Valkey service published on the host's internal ip. requirepass lives in the mounted valkey.conf
// (write-once, chmod 600) so the secret is not interpolated through a shell command. Stamped intentic.id=<id>
// so the binding provider can docker-exec valkey-cli into it.
const composeYaml = (id: string, parsed: ValkeyInputs): string =>
    [
        "services:",
        "  valkey:",
        `    image: ${parsed.image}`,
        "    restart: unless-stopped",
        "    command: [ valkey-server, /etc/valkey/valkey.conf ]",
        "    volumes:",
        "      - data:/data",
        "      - ./valkey.conf:/etc/valkey/valkey.conf:ro",
        `    ports: [ "${parsed.publishPort}:6379" ]`,
        `    labels: [ "intentic.id=${id}" ]`,
        "volumes: { data: {} }",
        "",
    ].join("\n");

const valkeyConf = (parsed: ValkeyInputs): string => [`requirepass ${parsed.adminPassword}`, "appendonly yes", ""].join("\n");

// Write compose + valkey.conf (both always). requirepass is a stable generated secret (same value every
// apply), so rewriting the conf is idempotent — no re-key risk, and the binding users + data (appendonly)
// persist across recreates.
const ensureFiles = async (session: SshSession, id: string, parsed: ValkeyInputs): Promise<void> => {
    const dir = stateDir(KIND, id);
    await session.exec(`mkdir -p ${dir}`);
    await session.exec(`cat > ${dir}/compose.yaml <<'COMPOSE_EOF'\n${composeYaml(id, parsed)}COMPOSE_EOF`);
    await session.exec(`cat > ${dir}/valkey.conf <<'CONF_EOF'\n${valkeyConf(parsed)}CONF_EOF`);
    await session.exec(`chmod 600 ${dir}/valkey.conf`);
};

const readyProbe = (id: string, parsed: ValkeyInputs): string =>
    `cid=$(docker ps -q --filter "label=intentic.id=${id}"); [ -n "$cid" ] && docker exec "$cid" valkey-cli -a '${parsed.adminPassword}' ping | grep -q PONG`;

// A Valkey backing instance (i.want.cache). read returns the resource once the container answers PONG (so a
// noop re-derives internalHost/port); diff drives an image-pin bump; apply is idempotent. Per-app ACL users
// are the binding provider's job.
export const createValkeyProvider = (executor: SshExecutor = sshExecutor): Provider => ({
    read: async (inputs, ctx) => {
        const parsed = parse(inputs);
        let session: SshSession;
        try {
            session = await executor.connect(sshTarget(parsed));
        } catch (error) {
            ctx.log(`valkey "${ctx.id}": host not reachable over SSH, treating as not-yet-created: ${String(error)}`);
            return undefined;
        }
        try {
            const probe = await session.exec(readyProbe(ctx.id, parsed));
            if (probe.code !== 0) {
                return undefined;
            }
            return { outputs: outputsFor(parsed), detail: { image: await containerImage(session, ctx.id) } };
        } finally {
            await session.dispose();
        }
    },
    diff: (inputs, observed) => {
        const parsed = parse(inputs);
        const image = (observed.detail?.["image"] ?? "") as string;
        return image === parsed.image
            ? { action: "noop" }
            : { action: "update", reason: `valkey image differs (running ${image}, want ${parsed.image})` };
    },
    apply: async (inputs, _observed, ctx) => {
        const parsed = parse(inputs);
        const session = await executor.connect(sshTarget(parsed));
        try {
            await ensureFiles(session, ctx.id, parsed);
            await composeUp(session, KIND, ctx.id);
            await waitReady(session, KIND, ctx.id, readyProbe(ctx.id, parsed), READY_TIMEOUT_MS);
            return outputsFor(parsed);
        } finally {
            await session.dispose();
        }
    },
    delete: async (inputs, ctx) => {
        const parsed = parse(inputs);
        const session = await executor.connect(sshTarget(parsed));
        try {
            await composeDown(session, KIND, ctx.id);
        } finally {
            await session.dispose();
        }
    },
});
