#!/usr/bin/env bash
# intentic local — run the whole intentic stack (Forgejo + Komodo + the AI-agent workspace + the Cloudflare
# tunnel) on a machine that is NOT exposed to the internet, with apps still reachable through your own
# Cloudflare account.
#
# How: this bootstraps a Docker-in-Docker + sshd "host" container on your PC and points intentic at it over
# SSH — so from intentic's view it is an ordinary server (`i.have.host({ address: "127.0.0.1", port: 2222 })`).
# `apply` then deploys cloudflared INTO that host; cloudflared dials OUTBOUND to Cloudflare's edge, so no
# inbound port / public IP is needed. This is the same DinD+SSH pattern the repo's e2e harness and `demo:up`
# already prove — productized as a standalone script.
#
# Usage:
#   intentic-local.sh up        # build host, deploy the full stack + tunnel (default)
#   intentic-local.sh down      # stop the host container (tunnel + DNS kept for a fast re-up)
#   intentic-local.sh clear     # also drop the host's docker-data volume (full local teardown)
#
# Required (env or interactive prompt):
#   CLOUDFLARE_API_TOKEN   Account→Cloudflare Tunnel:Edit, Zone→DNS:Edit, Zone→Zone:Read
#   INTENTIC_ZONE          a domain (zone) you own in that Cloudflare account, e.g. example.com
#
# Optional env:
#   INTENTIC_DIR     workspace dir for the intent/ + desired-state/ repos (default: ./intentic-local)
#   INTENTIC_CMD     how to invoke the CLI (default: "npx --yes @intentic/cli@latest").
#                    Maintainers testing from this repo: INTENTIC_CMD="pnpm intentic" INTENTIC_LINK=1
#   INTENTIC_LINK    set to 1 to `init --link` against this monorepo's local _libs (dev only)
#   SSH_PORT         host SSH port published to localhost (default: 2222)
#   FORGEJO_PORT     Forgejo port published to localhost for instant local browsing (default: 3000)
#   KOMODO_PORT      Komodo port published to localhost for instant local browsing (default: 9120)
set -euo pipefail

CONTAINER="intentic-host"
IMAGE="intentic-host:local"
DATA_VOLUME="intentic-host-docker"

SSH_PORT="${SSH_PORT:-2222}"
FORGEJO_PORT="${FORGEJO_PORT:-3000}"
KOMODO_PORT="${KOMODO_PORT:-9120}"
WORKDIR="${INTENTIC_DIR:-$PWD/intentic-local}"
INTENTIC_CMD="${INTENTIC_CMD:-npx --yes @intentic/cli@latest}"

log() { printf '▶ %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1 || die "missing required command: $1 ($2)"; }

# Run the intentic CLI. INTENTIC_CMD may be multi-word ("pnpm intentic" / "npx … @intentic/cli"), so split it.
intentic() {
    # shellcheck disable=SC2086
    $INTENTIC_CMD "$@"
}

# --- The DinD + sshd host image, embedded so this script is fully standalone (no repo, no published image).
# Identical to the repo's test/host: docker:28-dind gives an isolated daemon so intentic's nested containers
# (Forgejo, the CI runner, the Komodo compose stack, cloudflared) run exactly as on a real owned box, without
# touching your own Docker; sshd lets intentic reach it over SSH like real infra. iproute2/openssl back the
# host (`ip route`) and komodo (`openssl rand`) providers; docker-cli-compose backs `docker compose up`.
build_image() {
    local ctx
    ctx="$(mktemp -d)"
    cat >"$ctx/Dockerfile" <<'DOCKERFILE'
FROM docker:28-dind
RUN apk add --no-cache openssh openssh-server openssl iproute2 docker-cli-compose \
    && ssh-keygen -A \
    && mkdir -p /root/.ssh /run/sshd \
    && chmod 700 /root/.ssh \
    && printf 'PermitRootLogin prohibit-password\nPubkeyAuthentication yes\n' >> /etc/ssh/sshd_config
COPY entrypoint.sh /usr/local/bin/intentic-host-entrypoint.sh
RUN chmod +x /usr/local/bin/intentic-host-entrypoint.sh
EXPOSE 22
ENTRYPOINT ["/usr/local/bin/intentic-host-entrypoint.sh"]
DOCKERFILE
    cat >"$ctx/entrypoint.sh" <<'ENTRYPOINT'
#!/bin/sh
# Bring up the Docker daemon and sshd together: intentic SSHes in, then drives `docker` over that session.
set -e
dockerd-entrypoint.sh dockerd >/var/log/dockerd.log 2>&1 &
i=0
while [ "$i" -lt 60 ]; do
    if docker info >/dev/null 2>&1; then break; fi
    i=$((i + 1)); sleep 1
done
if [ -f /root/.ssh/authorized_keys ]; then chmod 600 /root/.ssh/authorized_keys; fi
exec /usr/sbin/sshd -D -e
ENTRYPOINT
    log "building the DinD host image ($IMAGE) …"
    docker build -t "$IMAGE" "$ctx" >/dev/null
    rm -rf "$ctx"
}

# The localhost intent: the DinD host over SSH on 127.0.0.1:$SSH_PORT, exposed through your Cloudflare account.
# Minimal by default (the agentic workspace + one app); the comment shows how to dial up to full parity.
write_config() {
    local zone="$1" path="$2"
    cat >"$path" <<CONFIG
import { env } from "@intentic/graph";
import { defineIntent } from "@intentic/sdk";

// Generated by intentic-local.sh. The "host" is a Docker-in-Docker container on this PC, reached over SSH
// exactly like a remote server; cloudflared is deployed into it by \`apply\` and dials outbound, so this works
// behind NAT with no inbound exposure.
export const intent = defineIntent((i) => {
    const host = i.have.host("host", {
        address: "127.0.0.1",
        user: "root",
        sshKey: env("HOST_SSH_KEY"),
        port: ${SSH_PORT},
    });

    const cf = i.have.cloudflare("cf", {
        apiToken: env("CLOUDFLARE_API_TOKEN"),
    });

    // The AI-agent workspace runner: a containerized dev sandbox for the project's repos, with live previews
    // served at the wildcard *.preview.${zone}.
    i.want.workspace("workspace", { on: host, expose: cf });

    // A sample app, shipped to one environment. Pushing a Dockerfile to its repo triggers CI/CD (build → push
    // → Komodo rolls it out) and it goes live at app.${zone}.
    i.want.app("app", {
        on: host,
        expose: cf,
        environments: {
            production: { domain: "app.${zone}", branch: "main" },
        },
    });

    // Full parity — uncomment to add observability, a database/cache, SSO, and object storage (heavier):
    //   const obs = i.want.service("obs", { kind: "signoz", on: host, expose: cf, domain: "signoz.${zone}" });
    //   const db = i.want.database("db", { on: host });
    //   const cache = i.want.cache("cache", { on: host });
    //   const auth = i.want.auth("auth", { on: host, expose: cf, domain: "auth.${zone}" });
    //   const store = i.want.objectStorage("store", { on: host, expose: cf, domain: "s3.${zone}" });
    // then wire them into the app: observe: obs, use: [db, cache, auth, store].
});
CONFIG
}

up() {
    need_cmd docker "install Docker"
    need_cmd ssh "install an OpenSSH client"
    need_cmd ssh-keygen "install OpenSSH"
    need_cmd node "install Node.js 24+"

    local token="${CLOUDFLARE_API_TOKEN:-}"
    if [ -z "$token" ]; then
        printf 'Cloudflare API token (Tunnel:Edit, DNS:Edit, Zone:Read): '
        read -r token
    fi
    [ -n "$token" ] || die "a Cloudflare API token is required"
    local zone="${INTENTIC_ZONE:-}"
    if [ -z "$zone" ]; then
        printf 'A domain you own in that Cloudflare account (e.g. example.com): '
        read -r zone
    fi
    [ -n "$zone" ] || die "a Cloudflare zone (your domain) is required"

    build_image

    log "starting the persistent DinD host ($CONTAINER) …"
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    # --privileged + DOCKER_TLS_CERTDIR="": dind needs privileges and a local (non-TLS) socket. The named
    # volume on /var/lib/docker persists the nested stack across `down`/`up`. --dns points the daemon at a
    # public resolver so it never hits a negative-caching local DNS for the just-created git.<zone> records.
    docker run -d --privileged \
        --name "$CONTAINER" \
        -e DOCKER_TLS_CERTDIR= \
        -v "$DATA_VOLUME:/var/lib/docker" \
        --dns 1.1.1.1 --dns 1.0.0.1 \
        -p "$SSH_PORT:22" \
        -p "$FORGEJO_PORT:3000" \
        -p "$KOMODO_PORT:9120" \
        "$IMAGE" >/dev/null

    log "generating a host SSH key and authorizing it …"
    mkdir -p "$WORKDIR"
    local key="$WORKDIR/.host_key"
    rm -f "$key" "$key.pub"
    ssh-keygen -t ed25519 -N "" -C "intentic-local" -f "$key" >/dev/null
    # Wait until `docker exec` works, then install the public key as the host's only authorized key.
    for _ in $(seq 1 60); do docker exec "$CONTAINER" true >/dev/null 2>&1 && break; sleep 1; done
    docker cp "$key.pub" "$CONTAINER:/root/.ssh/authorized_keys"
    # docker cp keeps the host file's uid, so the copy is not root-owned; sshd rejects a non-root-owned
    # authorized_keys ("bad ownership or modes"). Restore root ownership + 600 so pubkey auth is accepted.
    docker exec "$CONTAINER" sh -c 'chown root:root /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys'

    log "waiting for SSH on 127.0.0.1:$SSH_PORT …"
    local ok=0
    for _ in $(seq 1 90); do
        if ssh -i "$key" -p "$SSH_PORT" \
            -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -o ConnectTimeout=5 -o BatchMode=yes root@127.0.0.1 true >/dev/null 2>&1; then
            ok=1; break
        fi
        sleep 1
    done
    [ "$ok" = 1 ] || die "host SSH never came up (see: docker logs $CONTAINER)"

    log "scaffolding the intent (intentic init) …"
    if [ "${INTENTIC_LINK:-}" = 1 ]; then
        intentic init --dir "$WORKDIR" --link
    else
        intentic init --dir "$WORKDIR"
    fi

    local config="$WORKDIR/intent/deploy.config.ts"
    local artifact="$WORKDIR/desired-state/desired-state.json"
    local envfile="$WORKDIR/desired-state/.env"
    write_config "$zone" "$config"
    # The two externals intentic can't invent. The multi-line key is double-quoted, the format loadEnvFile reads.
    {
        printf 'HOST_SSH_KEY="'
        cat "$key"
        printf '"\n'
        printf 'CLOUDFLARE_API_TOKEN=%s\n' "$token"
    } >"$envfile"
    # A re-created host presents fresh keys; drop the trust-on-first-use cache so the new key re-pins cleanly.
    rm -f "$WORKDIR/desired-state/.known-hosts.json"

    log "resolve + apply — Forgejo + Komodo + the workspace runner + the Cloudflare tunnel …"
    intentic resolve --config "$config" --out "$artifact"
    intentic apply --artifact "$artifact" --maxIterations 8

    # The Forgejo/Komodo admin passwords are intentic-generated into .secrets.json during resolve/apply.
    local secrets="$WORKDIR/desired-state/.secrets.json"
    local fg_pw="" ko_pw=""
    if [ -f "$secrets" ]; then
        fg_pw="$(node -e 'const s=require(process.argv[1]);process.stdout.write(s.FORGEJO_ADMIN_PASSWORD||"")' "$secrets" 2>/dev/null || true)"
        ko_pw="$(node -e 'const s=require(process.argv[1]);process.stdout.write(s.KOMODO_ADMIN_PASSWORD||"")' "$secrets" 2>/dev/null || true)"
    fi

    cat <<SUMMARY

════════════════════════════════════════════════════════════════════
  intentic is UP on this PC and will stay up until \`intentic-local.sh down\`
════════════════════════════════════════════════════════════════════
  Public (through the Cloudflare tunnel — DNS/edge may take ~1 min):
    Forgejo  : https://git.$zone
    Komodo   : https://deploy.$zone
    App      : https://app.$zone        (after you push a Dockerfile to the app repo)
    Previews : https://<name>.preview.$zone
  Local (instant, no DNS needed):
    Forgejo  : http://127.0.0.1:$FORGEJO_PORT
    Komodo   : http://127.0.0.1:$KOMODO_PORT
  Admin login (intentic-generated):
    user      : intentic
    Forgejo pw: ${fg_pw:-<see $secrets>}
    Komodo pw : ${ko_pw:-<see $secrets>}
  SSH into the host:  ssh -i $WORKDIR/.host_key -p $SSH_PORT root@127.0.0.1
  Workspace dir    :  $WORKDIR   (edit intent/deploy.config.ts, then re-run \`up\`)
  Stop (fast re-up):  intentic-local.sh down
  Full teardown    :  intentic-local.sh clear
════════════════════════════════════════════════════════════════════
SUMMARY
}

# Stop without touching Cloudflare: remove the host container (which kills the cloudflared connector). The
# tunnel + DNS records are LEFT intact and the docker-data volume persists, so the next `up` reconnects fast.
down() {
    log "stopping the DinD host ($CONTAINER) — Cloudflare tunnel + DNS and the data volume are kept …"
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    log "stopped. \`intentic-local.sh up\` brings it back; \`intentic-local.sh clear\` also drops the data volume."
}

# Full local teardown: remove the host container AND its docker-data volume. The Cloudflare tunnel + DNS this
# created remain in your account — remove them from the Cloudflare dashboard (tunnel "intentic-host" + the
# git/deploy/app/preview records) if you want them gone.
clear_all() {
    log "removing the DinD host ($CONTAINER) and its data volume ($DATA_VOLUME) …"
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    docker volume rm "$DATA_VOLUME" >/dev/null 2>&1 || true
    log "cleared. The Cloudflare tunnel 'intentic-host' + git/deploy/app/preview DNS records remain — remove them in the Cloudflare dashboard if unwanted."
}

case "${1:-up}" in
    up) up ;;
    down) down ;;
    clear | clean) clear_all ;;
    *) die "usage: intentic-local.sh <up|down|clear>" ;;
esac
